### PR TITLE
validator: the code has been validated, so use it instead of trying to re-encode

### PR DESCRIPTION
**Pull request by oremj**

### CODE REVIEW

**Comment by oremj** [comment]
@pmac @matt-howell this PR will write exactly what is in the attribution_code parameter after validation, without re-encoding it. The current behavior is to validate and then re-encode.

Shall I merge this?

**Comment by matt-howell** [comment]
Looks like the change is to skip having to re-escape an unescaped version of the code by using the one that never got unescaped? Should be okay as far as I know.

**Comment by oremj** [comment]
Yep, that is correct.

**Comment by matt-howell** [comment]
Sounds good to me, then.

**Comment by pmac** [comment]
👍

**Pull request merged**
